// Brings a Claude Design badge delivery onto the shipped badge template.
//
// Deliveries have drawn their own take on "the round 2 template" (thinner
// ring, smaller glyph, different glow) and carry a C2PA metadata block. The
// app's 38 badges share one template, so we keep only each delivery's glyph
// and accent and set them on it. Light versions are then generated by
// scripts/light-badges.mjs, so every badge uses the same light colours.
//
//   node scripts/import-badges.mjs <delivery badges dir>
//   node scripts/light-badges.mjs

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const from = process.argv[2];
if (!from) { console.error('usage: node scripts/import-badges.mjs <dir>'); process.exit(1); }

const RGB = { '#7EE0C0': '126,224,192', '#F06C9B': '240,108,155', '#EF9F27': '239,159,39', '#35A26F': '53,162,111' };

function template(slug, accent, glyph) {
  const c = RGB[accent];
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
<defs>
<radialGradient id="${slug}-bloom" cx="0.5" cy="0.28" r="0.75"><stop offset="0" stop-color="rgba(${c},0.14)"></stop><stop offset="1" stop-color="rgba(${c},0)"></stop></radialGradient>
<radialGradient id="${slug}-glow" cx="0.5" cy="0.5" r="0.5"><stop offset="0.8" stop-color="rgba(${c},0)"></stop><stop offset="0.89" stop-color="rgba(${c},0.11)"></stop><stop offset="1" stop-color="rgba(${c},0)"></stop></radialGradient>
</defs>
<circle cx="256" cy="256" r="256" fill="url(#${slug}-glow)"></circle>
<circle cx="256" cy="256" r="225" fill="#141414"></circle>
<circle cx="256" cy="256" r="225" fill="url(#${slug}-bloom)"></circle>
<path d="M 63.7 145 A 222 222 0 0 1 448.3 145" fill="none" stroke="rgba(255,255,255,0.06)" stroke-width="6" stroke-linecap="round"></path>
<circle cx="256" cy="256" r="190" fill="none" stroke="rgba(${c},0.2)" stroke-width="7"></circle>
<g transform="translate(120 120) scale(11.3333)" fill="none" stroke="${accent}" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${glyph}</g>
</svg>
`;
}

// Glyphs we chose over the delivery's: its sunset/sunrise pair sat too close to
// Early Doors (also a sun on the horizon) at badge size. Lucide, same as theirs.
const GLYPH = {
  'day-into-night': '<path d="M12 2v2"></path><path d="M14.837 16.385a6 6 0 1 1-7.223-7.222c.624-.147.97.66.715 1.248a4 4 0 0 0 5.26 5.259c.589-.255 1.396.09 1.248.715"></path><path d="M16 12a4 4 0 0 0-4-4"></path><path d="m19 5-1.256 1.256"></path><path d="M20 12h2"></path>',
  'early-riser': '<circle cx="12" cy="13" r="8"></circle><path d="M12 9v4l2 2"></path><path d="M5 3 2 6"></path><path d="m22 6-3-3"></path><path d="M6.38 18.7 4 21"></path><path d="M17.64 18.67 20 21"></path>',
};

let n = 0;
for (const f of (await readdir(from)).filter((f) => f.endsWith('.svg') && !f.endsWith('-light.svg'))) {
  const s = await readFile(resolve(from, f), 'utf8');
  // The glyph is the one group scaled onto the 24 grid; its stroke is the accent.
  const g = s.match(/<g transform="translate\([^)]*\) scale\([^)]*\)"([^>]*)>([\s\S]*?)<\/g>/);
  const accent = g?.[1].match(/stroke="(#[0-9A-Fa-f]{6})"/)?.[1]?.toUpperCase();
  if (!g || !RGB[accent]) { console.warn(`skipped ${f}: no glyph group or unknown accent ${accent}`); continue; }
  const slug = basename(f, '.svg');
  await writeFile(resolve(root, `icons/badges/badge-${slug}.svg`), template(slug, accent, GLYPH[slug] || g[2].trim()));
  n++;
}
console.log(`imported ${n} badges into icons/badges/`);
